CREATE TABLE [dbo].[GoodsReceiptNotes](
	[GoodsReceiptNoteId] [int] IDENTITY(1,1) NOT NULL,
	[PurchaseOrderId] [int] NOT NULL,
	[GRNNumber] [nvarchar](100) NOT NULL,
	[ReceiptDate] [datetime] NULL,
	[Status] [nvarchar](50) NULL,
	[Remarks] [nvarchar](500) NULL,
	[CreatedDate] [datetime] NULL,
	[SellerId] [int] NULL,
	[CustomerId] [int] NULL,
	[SupplierId] [int] NULL,
	[TotalAmount] [decimal](18, 2) NOT NULL,
	[TotalQuantity] [decimal](18, 2) NOT NULL,
	[ReceivedQuantity] [decimal](18, 2) NOT NULL,
	[RejectedQuantity] [decimal](18, 2) NOT NULL,
	[UpdatedDate] [datetime2](7) NULL,
	[WarehouseId] [int] NULL,
	[GrnCode] [nvarchar](100) NULL,
	[FacilityCode] [nvarchar](100) NULL,
	[VendorCode] [nvarchar](100) NULL,
	[VendorInvoiceNumber] [nvarchar](100) NULL,
	[VendorInvoiceDate] [datetime] NULL,
	[InflowReceiptCode] [nvarchar](100) NULL,
	[GrnType] [nvarchar](50) NULL,
	[QcStatus] [nvarchar](50) NULL,
	[PutawayStatus] [nvarchar](50) NULL,
	[ChannelCode] [nvarchar](100) NULL,
	[PurchaseOrderCode] [nvarchar](100) NULL,
	[BatchId] [nvarchar](100) NULL,
	[SubTotal] [decimal](18, 2) NULL,
	[TaxAmount] [decimal](18, 2) NULL,
	[AcceptedQuantity] [decimal](18, 2) NULL,
	[PendingQuantity] [decimal](18, 2) NULL,
	[CurrencyCode] [nvarchar](10) NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[RowVersion] [timestamp] NOT NULL,
	[PurchaseOrderNumber] [nvarchar](100) NULL,
	[GRNStatus] [nvarchar](50) NULL,
	[WarehouseCode] [nvarchar](100) NULL,
	[BulkUploadStatus] [nvarchar](50) NULL,
	[IsBulkUpload] [bit] NULL,
	[UpdatedBy] [nvarchar](100) NULL,
	[IsCancelled] [bit] NULL,
	[VendorInvoiceDateCheckDisable] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[GoodsReceiptNoteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
