CREATE TABLE [dbo].[ProductInventories](
	[ProductInventoryId] [int] IDENTITY(1,1) NOT NULL,
	[SellerId] [int] NOT NULL,
	[CustomerId] [int] NOT NULL,
	[ProductId] [int] NOT NULL,
	[WarehouseId] [int] NULL,
	[LocationId] [int] NULL,
	[Quantity] [decimal](18, 2) NULL,
	[QuantityOnHand] [decimal](18, 2) NULL,
	[ReservedQuantity] [decimal](18, 2) NULL,
	[DamagedQuantity] [decimal](18, 2) NULL,
	[InTransitQuantity] [decimal](18, 2) NULL,
	[OpenSaleQuantity] [decimal](18, 2) NULL,
	[ReorderLevel] [decimal](18, 2) NULL,
	[ReorderQuantity] [decimal](18, 2) NULL,
	[LastStockUpdate] [datetime] NULL,
	[CreatedDate] [datetime] NOT NULL,
	[UpdatedDate] [datetime] NULL,
	[SKU] [nvarchar](100) NULL,
	[ItemTypeCode] [nvarchar](100) NULL,
	[VendorSkuCode] [nvarchar](100) NULL,
	[Barcode] [nvarchar](100) NULL,
	[WarehouseCode] [nvarchar](100) NULL,
	[FacilityCode] [nvarchar](100) NULL,
	[ChannelCode] [nvarchar](100) NULL,
	[LocationCode] [nvarchar](100) NULL,
	[LocationName] [nvarchar](200) NULL,
	[ShelfCode] [nvarchar](100) NULL,
	[LotNumber] [nvarchar](100) NULL,
	[BatchId] [nvarchar](100) NULL,
	[ChannelPrice] [decimal](18, 2) NULL,
	[StockType] [nvarchar](50) NULL,
	[InventoryType] [nvarchar](50) NULL,
	[InventoryStatus] [nvarchar](50) NULL,
	[BulkStatus] [nvarchar](50) NULL,
	[AdjustmentType] [nvarchar](50) NULL,
	[AdjustmentQuantity] [int] NULL,
	[IsBulkUpload] [bit] NULL,
	[RowVersion] [timestamp] NOT NULL,
	[ProductName] [nvarchar](500) NULL,
	[IsSyncedToUniware] [bit] NULL,
	[forceAllocate] [bit] NULL,
	[TransferToShelfCode] [varchar](50) NULL,
	[Sla] [int] NULL,
	[Remarks] [varchar](255) NULL,
	[BatchCode] [varchar](50) NULL,
	[FacilityCodeForUniware] [varchar](50) NULL,
	[ChannelCodeForUniware] [varchar](50) NULL,
	[Mrp] [decimal](18, 2) NULL,
	[Mfd] [bigint] NULL,
	[VendorCode] [varchar](50) NULL,
	[VendorBatchNumber] [varchar](50) NULL,
	[ExpiryDate] [datetime] NULL,
	[ManufacturingDate] [datetime] NULL,
	[IsFacilityCodeMatch] [bit] NULL,
	[IsChannelCodeMatch] [bit] NULL,
	[binCode] [nvarchar](50) NULL,
	[rackCode] [nvarchar](50) NULL,
	[batchNumber] [nvarchar](50) NULL,
	[lastSyncDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductInventoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
