CREATE TABLE [dbo].[Products](
	[ProductId] [int] IDENTITY(1,1) NOT NULL,
	[SellerId] [int] NOT NULL,
	[SKU] [nvarchar](100) NOT NULL,
	[ProductName] [nvarchar](250) NOT NULL,
	[Description] [nvarchar](max) NULL,
	[BrandId] [int] NULL,
	[CategoryId] [int] NULL,
	[ProductTypeId] [int] NULL,
	[Barcode] [nvarchar](100) NULL,
	[HSNCode] [nvarchar](20) NULL,
	[UnitOfMeasure] [nvarchar](50) NULL,
	[Weight] [decimal](18, 2) NULL,
	[Length] [decimal](18, 2) NULL,
	[Width] [decimal](18, 2) NULL,
	[Height] [decimal](18, 2) NULL,
	[Status] [nvarchar](50) NULL,
	[IsActive] [bit] NULL,
	[CreatedDate] [datetime] NULL,
	[UpdatedDate] [datetime] NULL,
	[CustomerId] [int] NOT NULL,
	[uom] [nvarchar](20) NULL,
	[quantityAmount] [decimal](18, 2) NULL,
	[totalAmount] [decimal](18, 2) NULL,
	[gstPer] [decimal](5, 2) NULL,
	[sgstPer] [decimal](5, 2) NULL,
	[sgstAmount] [decimal](18, 2) NULL,
	[cgstPer] [decimal](5, 2) NULL,
	[cgstAmount] [decimal](18, 2) NULL,
	[igstPer] [decimal](5, 2) NULL,
	[igstAmount] [decimal](18, 2) NULL,
	[afterGSTAmount] [decimal](18, 2) NULL,
	[taxType] [nvarchar](20) NULL,
	[mfgDate] [datetime] NULL,
	[expDate] [datetime] NULL,
	[exciseDutyTotalInWords] [nvarchar](500) NULL,
	[colorCode] [nvarchar](50) NULL,
	[remarks] [nvarchar](500) NULL,
	[isAdditionalCharges] [bit] NULL,
	[brandXID] [int] NULL,
	[itemXID] [int] NULL,
	[taxCategory] [nvarchar](50) NULL,
	[visibilityStatus] [nvarchar](20) NULL,
	[fulfillmentType] [nvarchar](20) NULL,
	[carrierType] [nvarchar](20) NULL,
	[readyToDispatchDays] [int] NULL,
	[shippingChargeLocal] [int] NULL,
	[shippingChargeRegional] [int] NULL,
	[shippingChargeNational] [int] NULL,
	[IsComboPack] [bit] NOT NULL,
	[ExternalProductId] [nvarchar](100) NULL,
	[ExternalSystemCode] [nvarchar](20) NULL,
	[flipkart_fsn] [varchar](16) NULL,
	[FulfillmentProfile] [nvarchar](50) NULL,
	[ShippingProvider] [nvarchar](50) NULL,
	[ProcurementType] [nvarchar](50) NULL,
	[ProcurementSla] [int] NULL,
	[BarcodeImageUrl] [nvarchar](1000) NULL,
	[BarcodeType] [nvarchar](50) NULL,
	[BarcodeDetailsJson] [nvarchar](max) NULL,
	[IsBarcodeVerified] [bit] NULL,
	[BarcodeVerifiedDate] [datetime] NULL,
	[BatchId] [nvarchar](100) NULL,
	[IsBulkUpload] [bit] NULL,
	[BulkUploadRowNumber] [int] NULL,
	[BulkUploadStatus] [nvarchar](100) NULL,
	[BulkUploadError] [nvarchar](2000) NULL,
	[CategoryCode] [nvarchar](200) NULL,
	[CategoryPath] [nvarchar](1000) NULL,
	[ChannelCode] [nvarchar](100) NULL,
	[ChannelItemId] [nvarchar](200) NULL,
	[ChannelProductId] [nvarchar](200) NULL,
	[IsChannelSynced] [bit] NULL,
	[LastChannelSyncDate] [datetime] NULL,
	[ChannelSyncStatus] [nvarchar](100) NULL,
	[BrandCode] [nvarchar](100) NULL,
	[ItemTypeCode] [nvarchar](100) NULL,
	[ShelfLife] [int] NULL,
	[ManufacturerDetails] [nvarchar](500) NULL,
	[CountryOfOrigin] [nvarchar](10) NULL,
	[IsInventorySyncEnabled] [bit] NULL,
	[IsPriceSyncEnabled] [bit] NULL,
	[ItemTypeName] [nvarchar](100) NULL,
	[ProductGroupCode] [nvarchar](100) NULL,
	[ProductDetailFieldColor] [nvarchar](100) NULL,
	[ProductDetailFieldSize] [nvarchar](100) NULL,
	[ProductDetailFieldMaterial] [nvarchar](100) NULL,
	[ProductDetailFieldsJson] [nvarchar](max) NULL,
	[DimUnit] [nvarchar](20) NULL,
	[WeightUnit] [nvarchar](20) NULL,
	[ShelfLifeType] [nvarchar](20) NULL,
	[ItemTypeStatus] [nvarchar](20) NULL,
	[TaxTypeCode] [nvarchar](50) NULL,
	[TaxPercentage] [decimal](18, 2) NULL,
	[Mrp] [decimal](18, 2) NULL,
	[SellingPrice] [decimal](18, 2) NULL,
	[CurrencyCode] [nvarchar](10) NULL,
	[VendorCode] [nvarchar](100) NULL,
	[VendorSkuCode] [nvarchar](100) NULL,
	[FacilityCode] [nvarchar](100) NULL,
	[ListingStatus] [nvarchar](50) NULL,
	[ProductCode] [nvarchar](100) NULL,
	[ItemType] [nvarchar](50) NULL,
	[ProductXID] [int] NULL,
	[CostPrice] [decimal](18, 2) NULL,
	[GSTPercentage] [decimal](5, 2) NULL,
	[IsReturnable] [bit] NULL,
	[IsCancellable] [bit] NULL,
	[IsCodAvailable] [bit] NULL,
	[ShelfLifeDays] [int] NULL,
	[WarrantyPeriod] [nvarchar](100) NULL,
	[IsSyncedToUniware] [bit] NULL,
	[Color] [nvarchar](50) NULL,
	[Size] [nvarchar](50) NULL,
	[ScanIdentifier] [nvarchar](100) NULL,
	[MinOrderSize] [int] NULL,
	[Features] [nvarchar](max) NULL,
	[ProductPageUrl] [nvarchar](500) NULL,
	[type] [varchar](20) NULL,
	[scanType] [varchar](20) NULL,
	[ean] [varchar](50) NULL,
	[batchGroupCode] [varchar](50) NULL,
	[enabled] [bit] NULL,
	[upc] [varchar](50) NULL,
	[isbn] [varchar](50) NULL,
	[basePrice] [decimal](18, 2) NULL,
	[gstTaxTypeCode] [varchar](50) NULL,
	[imageUrl] [varchar](500) NULL,
	[tat] [int] NULL,
	[expirable] [bit] NULL,
	[grnExpiryTolerance] [int] NULL,
	[dispatchExpiryTolerance] [int] NULL,
	[returnExpiryTolerance] [int] NULL,
	[requiresCustomization] [bit] NULL,
	[eanCode] [nvarchar](50) NULL,
	[upcCode] [nvarchar](50) NULL,
	[sellingPriceVal] [decimal](18, 2) NOT NULL,
	[isBatchEnabled] [bit] NOT NULL,
	[isExpiryEnabled] [bit] NOT NULL,
	[isSerialEnabled] [bit] NOT NULL,
	[ItemCode] [nvarchar](100) NULL,
	[ImporterDetails] [nvarchar](1000) NULL,
	[PackerDetails] [nvarchar](1000) NULL,
	[ShelfLifeSeconds] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
