CREATE TABLE [dbo].[PurchaseOrders](
	[PurchaseOrderId] [int] IDENTITY(1,1) NOT NULL,
	[SellerId] [int] NOT NULL,
	[SupplierId] [int] NOT NULL,
	[PurchaseOrderNumber] [nvarchar](100) NOT NULL,
	[OrderDate] [datetime] NULL,
	[ExpectedDeliveryDate] [datetime] NULL,
	[Status] [nvarchar](50) NULL,
	[TotalAmount] [decimal](18, 2) NULL,
	[Remarks] [nvarchar](500) NULL,
	[CreatedDate] [datetime] NULL,
	[UpdatedDate] [datetime] NULL,
	[CustomerId] [int] NULL,
	[WarehouseId] [int] NULL,
	[PurchaseOrderCode] [nvarchar](100) NULL,
	[VendorCode] [nvarchar](100) NULL,
	[VendorName] [nvarchar](200) NULL,
	[FacilityCode] [nvarchar](100) NULL,
	[Type] [nvarchar](20) NULL,
	[StatusCode] [nvarchar](100) NULL,
	[VendorAgreementName] [nvarchar](100) NULL,
	[ChannelCode] [nvarchar](100) NULL,
	[BatchId] [nvarchar](100) NULL,
	[ApprovedDate] [datetime] NULL,
	[CompletedDate] [datetime] NULL,
	[SubTotal] [decimal](18, 2) NULL,
	[TaxAmount] [decimal](18, 2) NULL,
	[DiscountAmount] [decimal](18, 2) NULL,
	[CurrencyCode] [nvarchar](10) NULL,
	[TotalItems] [int] NULL,
	[TotalQuantity] [decimal](18, 2) NULL,
	[InflowReceiptsCount] [int] NULL,
	[VendorInvoiceNumber] [nvarchar](100) NULL,
	[StateCode] [nvarchar](50) NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[RowVersion] [timestamp] NOT NULL,
	[CountryCode] [nvarchar](10) NULL,
	[ReceivedQuantity] [decimal](18, 2) NULL,
	[ShippingAddress] [nvarchar](500) NULL,
	[UpdatedBy] [nvarchar](100) NULL,
	[VendorInvoiceDate] [datetime2](7) NULL,
	[expiryDate] [datetime] NULL,
	[deliveryDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[PurchaseOrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
