CREATE TABLE [dbo].[SalesInvoiceItems](
	[SalesInvoiceItemId] [int] IDENTITY(1,1) NOT NULL,
	[SalesInvoiceId] [int] NOT NULL,
	[ProductId] [int] NOT NULL,
	[Quantity] [decimal](18, 2) NOT NULL,
	[UnitPrice] [decimal](18, 2) NOT NULL,
	[Discount] [decimal](18, 2) NOT NULL,
	[TaxAmount] [decimal](18, 2) NOT NULL,
	[TotalAmount] [decimal](18, 2) NOT NULL,
	[Pid] [int] NULL,
	[InvoiceXID] [int] NULL,
	[Description] [nvarchar](1000) NULL,
	[Uom] [nvarchar](50) NULL,
	[QuantityAmount] [decimal](18, 2) NULL,
	[InvoiceDiscountType] [int] NULL,
	[InvoiceDiscountValue] [decimal](18, 2) NULL,
	[InvoiceDiscountAmount] [decimal](18, 2) NULL,
	[TotalRateBeforeDiscount] [decimal](18, 2) NULL,
	[Hsncode] [nvarchar](50) NULL,
	[GstPer] [decimal](18, 2) NULL,
	[SgstPer] [decimal](18, 2) NULL,
	[SgstAmount] [decimal](18, 2) NULL,
	[CgstPer] [decimal](18, 2) NULL,
	[CgstAmount] [decimal](18, 2) NULL,
	[IgstPer] [decimal](18, 2) NULL,
	[IgstAmount] [decimal](18, 2) NULL,
	[AfterGSTAmount] [decimal](18, 2) NULL,
	[TaxType] [nvarchar](100) NULL,
	[MfgDate] [datetime2](7) NULL,
	[ExpDate] [datetime2](7) NULL,
	[Cases] [nvarchar](100) NULL,
	[ColorCode] [nvarchar](100) NULL,
	[ColorAmount] [decimal](18, 2) NULL,
	[Remarks] [nvarchar](1000) NULL,
	[ItemXID] [int] NULL,
	[BrandXID] [int] NULL,
	[IsReward] [bit] NULL,
	[IsAdditionalCharges] [bit] NULL,
	[MaterialTypeXid] [int] NULL,
	[SpecificationTypeXid] [int] NULL,
	[ProjectAssetDetailXID] [int] NULL,
	[SpecificationTypeDetailName] [nvarchar](500) NULL,
	[IsPurchasing] [bit] NULL,
 CONSTRAINT [PK_SalesInvoiceItems] PRIMARY KEY CLUSTERED 
(
	[SalesInvoiceItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
