CREATE TABLE [dbo].[SalesInvoices](
	[SalesInvoiceId] [int] IDENTITY(1,1) NOT NULL,
	[SalesOrderId] [int] NOT NULL,
	[InvoiceNumber] [nvarchar](100) NOT NULL,
	[InvoiceDate] [datetime] NOT NULL,
	[SubTotal] [decimal](18, 2) NOT NULL,
	[DiscountAmount] [decimal](18, 2) NOT NULL,
	[TaxAmount] [decimal](18, 2) NOT NULL,
	[TotalAmount] [decimal](18, 2) NOT NULL,
	[PaidAmount] [decimal](18, 2) NOT NULL,
	[BalanceAmount] [decimal](18, 2) NOT NULL,
	[PaymentStatus] [nvarchar](50) NULL,
	[Status] [nvarchar](50) NULL,
	[Remarks] [nvarchar](500) NULL,
	[CreatedDate] [datetime] NULL,
	[UpdatedDate] [datetime] NULL,
	[SellerId] [int] NOT NULL,
	[CustomerId] [int] NOT NULL,
	[InvoiceScenario] [nvarchar](100) NULL,
	[Category] [nvarchar](100) NULL,
	[TransactionType] [nvarchar](100) NULL,
	[UserGSTIN] [nvarchar](15) NULL,
	[DocumentType] [nvarchar](100) NULL,
	[SupplyType] [nvarchar](100) NULL,
	[PlaceOfSupply] [nvarchar](100) NULL,
	[FinancialYear] [nvarchar](20) NULL,
	[ReverseCharge] [bit] NOT NULL,
	[Id] [nvarchar](100) NULL,
	[RefId] [nvarchar](100) NULL,
	[CompanyName] [nvarchar](250) NULL,
	[MobileNo] [nvarchar](30) NULL,
	[EmailAddress] [nvarchar](250) NULL,
	[CompanyAddress] [nvarchar](500) NULL,
	[CompanyCity] [nvarchar](100) NULL,
	[CompanyState] [nvarchar](100) NULL,
	[CompanyPINCode] [nvarchar](20) NULL,
	[CustomerGSTIN] [nvarchar](15) NULL,
	[PurchaseOrderNo] [nvarchar](100) NULL,
	[PurchaseOrderDate] [datetime2](7) NULL,
	[OtherReferences] [nvarchar](500) NULL,
	[DespatchedDocumentNumber] [nvarchar](100) NULL,
	[StateCode] [nvarchar](20) NULL,
	[DeliveryNote] [nvarchar](250) NULL,
	[DeliveryNoteDate] [datetime2](7) NULL,
	[EWayBillNumber] [nvarchar](100) NULL,
	[VehicleNo] [nvarchar](100) NULL,
	[Distance] [nvarchar](50) NULL,
	[Transport] [nvarchar](250) NULL,
	[TransporterName] [nvarchar](250) NULL,
	[TransporterID] [nvarchar](100) NULL,
	[TransporterDocNo] [nvarchar](100) NULL,
	[TransportMode] [nvarchar](100) NULL,
	[Destination] [nvarchar](250) NULL,
	[BillOfLandingOrLRRRNo] [nvarchar](150) NULL,
	[DespatchedThrough] [nvarchar](250) NULL,
	[ModeOrTermsOfPayment] [nvarchar](250) NULL,
	[PaymentMode] [nvarchar](100) NULL,
	[IrnNumber] [nvarchar](500) NULL,
	[AckNo] [nvarchar](100) NULL,
	[AckDate] [datetime2](7) NULL,
	[SignedQRCode] [nvarchar](max) NULL,
	[SignedInvoice] [nvarchar](max) NULL,
	[ShipToCompanyName] [nvarchar](200) NULL,
	[ShipToLegalName] [nvarchar](200) NULL,
	[ShipToGSTIN] [nvarchar](30) NULL,
	[ShipToAddress] [nvarchar](500) NULL,
	[ShipToCity] [nvarchar](100) NULL,
	[ShipToState] [nvarchar](100) NULL,
	[ShipToStateCode] [nvarchar](10) NULL,
	[ShipToPinCode] [nvarchar](20) NULL,
	[ShipToPhone] [nvarchar](50) NULL,
	[ShipToEmail] [nvarchar](100) NULL,
	[DispatchFromCompanyName] [nvarchar](200) NULL,
	[DispatchFromLegalName] [nvarchar](200) NULL,
	[DispatchFromGSTIN] [nvarchar](30) NULL,
	[DispatchFromAddress] [nvarchar](500) NULL,
	[DispatchFromCity] [nvarchar](100) NULL,
	[DispatchFromState] [nvarchar](100) NULL,
	[DispatchFromStateCode] [nvarchar](10) NULL,
	[DispatchFromPinCode] [nvarchar](20) NULL,
	[DispatchFromPhone] [nvarchar](50) NULL,
	[shippingPackageCode] [varchar](50) NULL,
	[channelCode] [varchar](50) NULL,
	[fromPartyCode] [varchar](50) NULL,
	[toPartyCode] [varchar](50) NULL,
	[destinationStateCode] [varchar](10) NULL,
	[destinationCountryCode] [varchar](2) NULL,
	[type] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[SalesInvoiceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
