CREATE TABLE [dbo].[SalesOrderItems](
	[SalesOrderItemId] [int] IDENTITY(1,1) NOT NULL,
	[SalesOrderId] [int] NOT NULL,
	[ProductId] [int] NOT NULL,
	[Quantity] [decimal](18, 2) NOT NULL,
	[UnitPrice] [decimal](18, 2) NOT NULL,
	[Discount] [decimal](18, 2) NOT NULL,
	[TaxAmount] [decimal](18, 2) NOT NULL,
	[TotalAmount] [decimal](18, 2) NOT NULL,
	[pid] [int] NULL,
	[invoiceXID] [int] NULL,
	[description] [nvarchar](500) NULL,
	[uom] [nvarchar](20) NULL,
	[quantityAmount] [decimal](18, 2) NULL,
	[invoiceDiscountType] [int] NULL,
	[invoiceDiscountValue] [decimal](18, 2) NULL,
	[invoiceDiscountAmount] [decimal](18, 2) NULL,
	[totalRateBeforeDiscount] [decimal](18, 2) NULL,
	[hsncode] [nvarchar](20) NULL,
	[gstPer] [decimal](5, 2) NULL,
	[sgstPer] [decimal](5, 2) NULL,
	[sgstAmount] [decimal](18, 2) NULL,
	[cgstPer] [decimal](5, 2) NULL,
	[cgstAmount] [decimal](18, 2) NULL,
	[igstPer] [decimal](5, 2) NULL,
	[igstAmount] [decimal](18, 2) NULL,
	[afterGSTAmount] [decimal](18, 2) NULL,
	[mfgDate] [datetime] NULL,
	[expDate] [datetime] NULL,
	[cases] [nvarchar](50) NULL,
	[taxType] [nvarchar](20) NULL,
	[colorCode] [nvarchar](50) NULL,
	[colorAmount] [decimal](18, 2) NULL,
	[remarks] [nvarchar](500) NULL,
	[itemXID] [int] NULL,
	[brandXID] [int] NULL,
	[isReward] [bit] NULL,
	[isAdditionalCharges] [bit] NULL,
	[materialTypeXid] [int] NULL,
	[specificationTypeXid] [int] NULL,
	[projectAssetDetailXID] [int] NULL,
	[specificationTypeDetailName] [nvarchar](200) NULL,
	[isPurchasing] [bit] NULL,
	[ChannelSkuCode] [nvarchar](100) NULL,
	[FacilityCode] [nvarchar](100) NULL,
	[Sku] [nvarchar](100) NULL,
	[Status] [nvarchar](50) NULL,
	[FulfillmentStatus] [nvarchar](50) NULL,
	[Mrp] [decimal](18, 2) NULL,
	[SellingPrice] [decimal](18, 2) NULL,
	[ChannelProductId] [nvarchar](100) NULL,
	[VendorSkuCode] [nvarchar](100) NULL,
	[ChannelSaleOrderItemCode] [nvarchar](100) NULL,
	[PacketNumber] [int] NULL,
	[ChannelSaleOrderId] [nvarchar](100) NULL,
	[SubTotal] [decimal](18, 2) NULL,
	[DiscountPer] [decimal](18, 2) NULL,
	[ChannelProductName] [nvarchar](200) NULL,
	[DisplayName] [nvarchar](200) NULL,
	[ProductName] [nvarchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[SalesOrderItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
