CREATE TABLE [dbo].[SalesOrders](
	[SalesOrderId] [int] IDENTITY(1,1) NOT NULL,
	[SellerId] [int] NOT NULL,
	[CustomerId] [int] NOT NULL,
	[SalesOrderNumber] [nvarchar](100) NOT NULL,
	[OrderDate] [datetime] NOT NULL,
	[Status] [nvarchar](50) NOT NULL,
	[TotalAmount] [decimal](18, 2) NOT NULL,
	[Remarks] [nvarchar](500) NULL,
	[CreatedDate] [datetime] NOT NULL,
	[UpdatedDate] [datetime] NULL,
	[company_Name] [nvarchar](200) NULL,
	[company_City] [nvarchar](100) NULL,
	[transport] [nvarchar](100) NULL,
	[transporterDocNo] [nvarchar](100) NULL,
	[vehicleNo] [nvarchar](20) NULL,
	[eWayBillNumber] [nvarchar](100) NULL,
	[deliveryNote] [nvarchar](100) NULL,
	[company_Address] [nvarchar](500) NULL,
	[company_State] [nvarchar](100) NULL,
	[company_PINCode] [nvarchar](10) NULL,
	[phone_no] [nvarchar](20) NULL,
	[email_Address] [nvarchar](200) NULL,
	[gstin] [nvarchar](20) NULL,
	[modeorTermsOfPayment] [nvarchar](200) NULL,
	[otherReferences] [nvarchar](200) NULL,
	[despatchedDocumentNumber] [nvarchar](100) NULL,
	[deliveryNoteDate] [datetime] NULL,
	[distance] [nvarchar](20) NULL,
	[tYear] [nvarchar](10) NULL,
	[transporterName] [nvarchar](200) NULL,
	[transporterID] [nvarchar](100) NULL,
	[transportMode] [nvarchar](50) NULL,
	[stateCode] [nvarchar](10) NULL,
	[pid] [int] NULL,
	[keyID] [int] NULL,
	[TransactionType] [nvarchar](50) NULL,
	[ShipToGSTIN] [nvarchar](15) NULL,
	[ShipToCompanyName] [nvarchar](250) NULL,
	[ShipToLegalName] [nvarchar](250) NULL,
	[ShipToAddress] [nvarchar](500) NULL,
	[ShipToCity] [nvarchar](100) NULL,
	[ShipToState] [nvarchar](100) NULL,
	[ShipToStateCode] [nvarchar](10) NULL,
	[ShipToPinCode] [nvarchar](10) NULL,
	[ShipToPhone] [nvarchar](20) NULL,
	[ShipToEmail] [nvarchar](250) NULL,
	[DispatchFromGSTIN] [nvarchar](15) NULL,
	[DispatchFromCompanyName] [nvarchar](250) NULL,
	[DispatchFromLegalName] [nvarchar](250) NULL,
	[DispatchFromAddress] [nvarchar](500) NULL,
	[DispatchFromCity] [nvarchar](100) NULL,
	[DispatchFromState] [nvarchar](100) NULL,
	[DispatchFromStateCode] [nvarchar](10) NULL,
	[DispatchFromPinCode] [nvarchar](10) NULL,
	[DispatchFromPhone] [nvarchar](20) NULL,
	[IrnNumber] [nvarchar](500) NULL,
	[AckNo] [nvarchar](100) NULL,
	[AckDate] [datetime2](7) NULL,
	[SignedQRCode] [nvarchar](max) NULL,
	[BillOfLandingOrLRRRNo] [nvarchar](100) NULL,
	[DespatchedThrough] [nvarchar](100) NULL,
	[Destination] [nvarchar](100) NULL,
	[PurchaseOrderNo] [nvarchar](100) NULL,
	[PurchaseOrderDate] [datetime2](7) NULL,
	[SignedInvoice] [nvarchar](max) NULL,
	[DisplayOrderCode] [nvarchar](100) NULL,
	[ChannelOrderId] [nvarchar](100) NULL,
	[ExternalOrderId] [nvarchar](100) NULL,
	[ChannelCode] [nvarchar](50) NULL,
	[PaymentMethodCode] [nvarchar](50) NULL,
	[PaymentMethod] [nvarchar](50) NULL,
	[CurrencyCode] [nvarchar](10) NULL,
	[ShippingMethodCode] [nvarchar](50) NULL,
	[CourierCode] [nvarchar](50) NULL,
	[CustomerCode] [nvarchar](50) NULL,
	[CustomerName] [nvarchar](200) NULL,
	[CustomerEmail] [nvarchar](200) NULL,
	[CustomerPhone] [nvarchar](20) NULL,
	[CodAmount] [decimal](18, 2) NULL,
	[FulfillmentTat] [nvarchar](100) NULL,
	[IsThirdPartyShipping] [bit] NULL,
	[IsGiftWrap] [bit] NULL,
	[GiftMessage] [nvarchar](500) NULL,
	[NotificationEmail] [nvarchar](200) NULL,
	[NotificationMobile] [nvarchar](20) NULL,
	[SubTotal] [decimal](18, 2) NULL,
	[DiscountAmount] [decimal](18, 2) NULL,
	[TaxAmount] [decimal](18, 2) NULL,
	[ShippingAmount] [decimal](18, 2) NULL,
	[RoundOffAmount] [decimal](18, 2) NULL,
	[BillingAddressId] [int] NULL,
	[ShippingAddressId] [int] NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[UpdatedBy] [nvarchar](100) NULL,
	[IsCancelled] [bit] NULL,
	[CancelledDate] [datetime] NULL,
	[CancelReason] [nvarchar](500) NULL,
	[RowVersion] [timestamp] NOT NULL,
	[SalesOrderCode] [nvarchar](100) NULL,
	[FacilityCode] [nvarchar](100) NULL,
	[Type] [nvarchar](50) NULL,
	[ChannelCreatedDate] [datetime] NULL,
	[ExpectedDeliveryDate] [datetime] NULL,
	[StatusCode] [nvarchar](50) NULL,
	[FulfillmentStatus] [nvarchar](50) NULL,
	[TotalQuantity] [decimal](18, 2) NULL,
	[TotalItems] [int] NULL,
	[ShippingAddress] [nvarchar](500) NULL,
	[BillingAddress] [nvarchar](500) NULL,
	[CountryCode] [nvarchar](10) NULL,
	[ShippingCharges] [decimal](18, 2) NULL,
	[SupplierRef] [nvarchar](200) NULL,
	[BuyersOrderNo] [nvarchar](100) NULL,
	[BuyersOrderDate] [datetime] NULL,
	[TermsOfDelivery] [nvarchar](200) NULL,
	[RoundOff] [decimal](18, 2) NULL,
	[TotalInWords] [nvarchar](500) NULL,
	[GrnCode] [nvarchar](100) NULL,
	[GRNNumber] [nvarchar](100) NULL,
	[GoodsReceiptNoteId] [int] NULL,
	[ShippingAddressLine1] [nvarchar](500) NULL,
	[ShippingCity] [nvarchar](100) NULL,
	[ShippingState] [nvarchar](100) NULL,
	[ShippingPincode] [nvarchar](20) NULL,
	[cashOnDelivery] [bit] NULL,
	[paymentInstrument] [varchar](20) NULL,
	[billingAddressReferenceId] [varchar](50) NULL,
	[shippingAddressReferenceId] [varchar](50) NULL,
	[ChannelProcessingTime] [datetime] NULL,
	[CustomerGSTIN] [varchar](15) NULL,
	[Priority] [int] NULL,
	[VerificationRequired] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[SalesOrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
