CREATE TABLE [dbo].[Sellers](
	[SellerId] [int] IDENTITY(1,1) NOT NULL,
	[SellerCode] [nvarchar](50) NOT NULL,
	[SellerName] [nvarchar](200) NOT NULL,
	[GSTIN] [nvarchar](20) NULL,
	[PAN] [nvarchar](20) NULL,
	[Email] [nvarchar](150) NULL,
	[Phone] [nvarchar](20) NULL,
	[AddressLine1] [nvarchar](250) NULL,
	[AddressLine2] [nvarchar](250) NULL,
	[City] [nvarchar](100) NULL,
	[State] [nvarchar](100) NULL,
	[Country] [nvarchar](100) NULL,
	[PostalCode] [nvarchar](20) NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[UpdatedDate] [datetime] NULL,
	[Address] [nvarchar](500) NULL,
	[CompanyName] [nvarchar](200) NULL,
	[ContactPerson] [nvarchar](200) NULL,
	[CreatedAt] [datetime] NULL,
	[UpdatedAt] [datetime] NULL,
	[TradeName] [nvarchar](200) NULL,
	[LegalName] [nvarchar](200) NULL,
	[BuildingName] [nvarchar](200) NULL,
	[Location] [nvarchar](200) NULL,
	[StateCode] [nvarchar](10) NULL,
	[FloorNo] [nvarchar](50) NULL,
	[website] [nvarchar](255) NULL,
	[details] [nvarchar](max) NULL,
	[pincode] [nvarchar](20) NULL,
	[bankName] [nvarchar](255) NULL,
	[bankAccount] [nvarchar](100) NULL,
	[bankIfsc] [nvarchar](50) NULL,
	[bankBranch] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[SellerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
