CREATE TABLE [dbo].[Shipments](
	[ShipmentId] [int] IDENTITY(1,1) NOT NULL,
	[OrderId] [int] NOT NULL,
	[CourierName] [nvarchar](150) NULL,
	[TrackingNumber] [nvarchar](150) NULL,
	[ShipmentDate] [datetime] NULL,
	[DeliveryDate] [datetime] NULL,
	[ShipmentStatus] [nvarchar](50) NULL,
	[SellerId] [int] NOT NULL,
	[CustomerId] [int] NOT NULL,
	[SalesOrderId] [int] NULL,
	[DeliveryChallanId] [int] NULL,
	[SalesOrderNumber] [nvarchar](100) NULL,
	[DisplayOrderCode] [nvarchar](100) NULL,
	[ShipmentNumber] [nvarchar](100) NULL,
	[ShippingPackageCode] [nvarchar](100) NULL,
	[ShippingPackageNumber] [nvarchar](100) NULL,
	[ChannelCode] [nvarchar](100) NULL,
	[FacilityCode] [nvarchar](100) NULL,
	[CourierCode] [nvarchar](100) NULL,
	[ShippingMethodCode] [nvarchar](100) NULL,
	[AwbNumber] [nvarchar](200) NULL,
	[CourierTrackingUrl] [nvarchar](500) NULL,
	[ShippingLabelUrl] [nvarchar](500) NULL,
	[IsCod] [bit] NOT NULL,
	[CodAmount] [decimal](18, 2) NULL,
	[ExpectedDeliveryDate] [datetime] NULL,
	[ActualDeliveryDate] [datetime] NULL,
	[ShippingPackageStatus] [nvarchar](50) NULL,
	[Length] [decimal](18, 2) NULL,
	[Width] [decimal](18, 2) NULL,
	[Height] [decimal](18, 2) NULL,
	[Weight] [decimal](18, 2) NULL,
	[VehicleNo] [nvarchar](50) NULL,
	[TransporterName] [nvarchar](200) NULL,
	[EWayBillNumber] [nvarchar](100) NULL,
	[ShippingCharges] [decimal](18, 2) NULL,
	[CreatedDate] [datetime] NULL,
	[RowVersion] [timestamp] NOT NULL,
	[CourierStatus] [nvarchar](50) NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[DimUnit] [nvarchar](20) NULL,
	[InvoiceUrl] [nvarchar](500) NULL,
	[ReturnDate] [datetime2](7) NULL,
	[ShippingAddress] [nvarchar](500) NULL,
	[StatusRemarks] [nvarchar](500) NULL,
	[TransportMode] [nvarchar](50) NULL,
	[TransporterDocNo] [nvarchar](100) NULL,
	[TransporterID] [nvarchar](100) NULL,
	[UpdatedDate] [datetime2](7) NULL,
	[WeightUnit] [nvarchar](20) NULL,
	[UpdatedBy] [nvarchar](100) NULL,
	[Status] [nvarchar](50) NULL,
	[Distance] [nvarchar](50) NULL,
	[TotalAmount] [decimal](18, 2) NULL,
	[saleOrderCode] [varchar](50) NULL,
	[shippingProviderCode] [varchar](50) NULL,
	[actualWeight] [decimal](18, 2) NULL,
	[invoiceCode] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ShipmentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
