CREATE TABLE [dbo].[Warehouses](
	[WarehouseId] [int] IDENTITY(1,1) NOT NULL,
	[SellerId] [int] NOT NULL,
	[WarehouseCode] [nvarchar](50) NOT NULL,
	[WarehouseName] [nvarchar](200) NOT NULL,
	[AddressLine1] [nvarchar](250) NULL,
	[AddressLine2] [nvarchar](250) NULL,
	[City] [nvarchar](100) NULL,
	[State] [nvarchar](100) NULL,
	[Country] [nvarchar](100) NULL,
	[PostalCode] [nvarchar](20) NULL,
	[ContactPerson] [nvarchar](150) NULL,
	[Phone] [nvarchar](20) NULL,
	[Email] [nvarchar](150) NULL,
	[IsActive] [bit] NULL,
	[CreatedDate] [datetime] NULL,
	[UpdatedDate] [datetime] NULL,
	[CustomerId] [int] NULL,
	[pan] [nvarchar](20) NULL,
	[arn] [nvarchar](50) NULL,
	[tinNo] [nvarchar](50) NULL,
	[cstNo] [nvarchar](50) NULL,
	[eccNo] [nvarchar](50) NULL,
	[fax] [nvarchar](50) NULL,
	[heading] [nvarchar](200) NULL,
	[imageName] [nvarchar](200) NULL,
	[imagePath] [nvarchar](500) NULL,
	[backgroundImageName] [nvarchar](200) NULL,
	[backgroundImagePath] [nvarchar](500) NULL,
	[companySignature] [nvarchar](200) NULL,
	[companyTallyName] [nvarchar](200) NULL,
	[businessTypeXID] [int] NULL,
	[poBox] [nvarchar](20) NULL,
	[ExternalLocationId] [nvarchar](100) NULL,
	[ExternalSystemCode] [nvarchar](20) NULL,
	[flipkart_location_id] [varchar](50) NULL,
	[FacilityCode] [nvarchar](100) NULL,
	[IsFacilityCodeMatch] [bit] NULL,
	[FacilityName] [nvarchar](200) NULL,
	[FacilityType] [nvarchar](100) NULL,
	[LocationCode] [nvarchar](100) NULL,
	[StateCode] [nvarchar](10) NULL,
	[CountryCode] [nvarchar](10) NULL,
	[ChannelCode] [nvarchar](100) NULL,
	[GSTNumber] [nvarchar](50) NULL,
	[IsDefault] [bit] NULL,
	[IsQCEnabled] [bit] NULL,
	[IsPutawayEnabled] [bit] NULL,
	[CreatedBy] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[WarehouseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
